### ISSUE TITLE
extract_mesh.py - CUDA memory allocation exceeding 100+ GiB

### ISSUE THREAD

**Issue by andreasHovaldt** [autonomousvision/gaussian-opacity-fields#96]
Hello,
Firstly thank you for this amazing contribution :)

I have been trying to get a mesh extraction pipeline up and running, thus currently I have only been trying out GOF on the Mip-NeRF 360 scenes. The training process works perfectly, but when I try to run "extract_mest.py" on the scenes, I run into problems with incredibly high memory allocation requirements.
Any help with this problem would be highly appreciated!

#### Command
```OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=0 python extract_mesh.py -m exp_360/release/garden --iteration 30000```

#### Output
```
Looking for config file in exp_360/release/garden/cfg_args
Config file found: exp_360/release/garden/cfg_args
Rendering exp_360/release/garden
Loading trained model at iteration 30000
Reading camera 185/185
Loading Training Cameras
Traceback (most recent call last):
  File "/home/andreas/Github/gaussian-opacity-fields/extract_mesh.py", line 163, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args), args.filter_mesh, args.texture_mesh, args.near, args.far)
  File "/home/andreas/Github/gaussian-opacity-fields/extract_mesh.py", line 141, in extract_mesh
    marching_tetrahedra_with_binary_search(dataset.model_path, "test", iteration, cams, gaussians, pipeline, background, kernel_size, filter_mesh, texture_mesh, near, far)
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/andreas/Github/gaussian-opacity-fields/extract_mesh.py", line 43, in marching_tetrahedra_with_binary_search
    points, points_scale = gaussians.get_tetra_points(views, near, far)
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/andreas/Github/gaussian-opacity-fields/scene/gaussian_model.py", line 462, in get_tetra_points
    vertex_mask = get_frustum_mask(vertices, views, near, far)
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/andreas/Github/gaussian-opacity-fields/scene/gaussian_model.py", line 56, in get_frustum_mask
    view_points = einsum(view_matrices, homo_points, "n_view b c, N c -> n_view N b")
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/einops/einops.py", line 907, in einsum
    return get_backend(tensors[0]).einsum(pattern, *tensors)
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/einops/_backends.py", line 287, in einsum
    return self.torch.einsum(pattern, *x)
  File "/home/andreas/miniforge3/envs/gof2/lib/python3.9/site-packages/torch/functional.py", line 402, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 139.69 GiB. GPU 0 has a total capacity of 23.65 GiB of which 16.11 GiB is free. Including non-PyTorch memory, this process has 7.52 GiB memory in use. Of the allocated memory 6.09 GiB is allocated by PyTorch, and 971.39 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

This example was taken when I tried to run ```python scripts/run_mipnerf360.py```, but I have also tried manually running the ```train.py``` and ```extract_mesh.py``` scripts which end up with a similar error message.

Edit: I have now done it on a handful of the different scenes in the Mip-NeRF 360 dataset, and the memory allocation crashes happen with allocations ranging from 40GiB to 140GiB.

### Runtime info
Graphics Card: RTX 4090
Operating System: Ubuntu 24.04.1 LTS x86_64
nvcc version: Build cuda_12.4.r12.4/compiler.34097967_0
C++ compiler: 9.5.0

**Comment by niujinshuchong** [comment]
Hi, thanks for reporting this. I merged the code without testing it on a larger scenes. You can try to use a previous commit https://github.com/autonomousvision/gaussian-opacity-fields/commit/a3ca467ef6249b42ff55d7c562ba91dcff5e11af or you can update the this part with a for loop: https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/scene/gaussian_model.py#L54-L71.

**Comment by andreasHovaldt** [comment]
Thank you for the response, I switched to the mentioned commit which fixed the problem :)

**Comment by DailyInsistence** [comment]
> 感谢您的回复，我切换到上述的提交，解决了该问题:)

Should I re-git clone the commit a3ca467?

**Comment by tang184** [comment]
Encounter same issue. The issue can only be fixed with previous commit.

**Comment by zxy-bjtu** [comment]
I'm encountering the same issue. When using a previous commit (e.g., from the dev branch), I can successfully extract meshes from the mipnerf360 dataset, but the following three scenes still fail: ["bicycle", "stump", "treehill"]. The other six scenes work correctly. Would it be possible to reduce GPU memory usage through parameter tuning?

For example, I failed to extract "treehill" via RTX3090:
```shell
Rendering progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████                                                                                          ████████████████████████████████████████████████████████| 169/169 [03:43<00:00,  1.32s/it]
torch.Size([1, 37345725, 3]) torch.Size([250199980, 4]) torch.Size([37345725])
Traceback (most recent call last):
  File "/data1/thesis_project/GOF/extract_mesh.py", line 161, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args), args.filter_mesh, args.texture_mesh)
  File "/data1/thesis_project/GOF/extract_mesh.py", line 141, in extract_mesh
    marching_tetrahedra_with_binary_search(dataset.model_path, "test", iteration, cams, gaussians, pipeline, background, kernel_size, filter_mesh, texture_mesh)
  File "/home/zxy/.conda/envs/sugar/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data1/thesis_project/GOF/extract_mesh.py", line 70, in marching_tetrahedra_with_binary_search
    verts_list, scale_list, faces_list, _ = marching_tetrahedra(vertices, tets, sdf, points_scale[None])
  File "/data1/thesis_project/GOF/utils/tetmesh.py", line 189, in marching_tetrahedra
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/data1/thesis_project/GOF/utils/tetmesh.py", line 189, in <listcomp>
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/data1/thesis_project/GOF/utils/tetmesh.py", line 63, in _unbatched_marching_tetrahedra
    verts, verts_scales, faces, verts_ids = _unbatched_marching_tetrahedra(vertices, tet_chunk, sdf, scales)
  File "/data1/thesis_project/GOF/utils/tetmesh.py", line 110, in _unbatched_marching_tetrahedra
    unique_edges, idx_map = torch.unique(all_edges, dim=0, return_inverse=True)
  File "/home/zxy/.conda/envs/sugar/lib/python3.9/site-packages/torch/_jit_internal.py", line 482, in fn
    return if_true(*args, **kwargs)
  File "/home/zxy/.conda/envs/sugar/lib/python3.9/site-packages/torch/_jit_internal.py", line 484, in fn
    return if_false(*args, **kwargs)
  File "/home/zxy/.conda/envs/sugar/lib/python3.9/site-packages/torch/functional.py", line 895, in _return_inverse
    output, inverse_indices, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/zxy/.conda/envs/sugar/lib/python3.9/site-packages/torch/functional.py", line 791, in _unique_impl
    output, inverse_indices, counts = _VF.unique_dim(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 404.00 MiB (GPU 0; 23.69 GiB total capacity; 19.80 GiB already allocated; 402.62 MiB free; 21.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Runtime info**
Graphics Card: RTX 3090
Operating System: Ubuntu18.04 LTS x86_64
